/**
 * Copyright 2021 Aldrin Mathew

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */

import { ColorHex } from './Color';

export const Colors = {
    black: ColorHex('#000000FF'),
    white: ColorHex('#FFFFFFFF'),
    red: ColorHex('#FF0000FF'),
    darkRed: ColorHex('#8B0000FF'),
    green: ColorHex('#008000FF'),
    lightGreen: ColorHex('#90EE90FF'),
    darkGreen: ColorHex('#006400FF'),
    blue: ColorHex('#0000FFFF'),
    lightBlue: ColorHex('#ADD8E6FF'),
    darkBlue: ColorHex('#00008BFF'),

    transparent: ColorHex('#00000000'),

    aliceBlue: ColorHex('#F0F8FFFF'),
    antiqueWhite: ColorHex('#FAEBD7FF'),
    aqua: ColorHex('#00FFFFFF'),
    aquamarine: ColorHex('#7FFFD4FF'),
    azure: ColorHex('#F0FFFFFF'),
    beige: ColorHex('#F5F5DCFF'),
    bisque: ColorHex('#FFE4C4FF'),
    blanchedAlmond: ColorHex('#FFEBCDFF'),
    blueViolet: ColorHex('#8A2BE2FF'),
    brown: ColorHex('#A52A2AFF'),
    burlyWood: ColorHex('#DEB887FF'),
    cadetBlue: ColorHex('#5F9EA0FF'),
    chartreuse: ColorHex('#7FFF00FF'),
    chocolate: ColorHex('#D2691EFF'),
    coral: ColorHex('#FF7F50FF'),
    cornflowerBlue: ColorHex('#6495EDFF'),
    cornsilk: ColorHex('#FFF8DCFF'),
    crimson: ColorHex('#DC143CFF'),
    cyan: ColorHex('#00FFFFFF'),
    darkCyan: ColorHex('#008B8BFF'),
    darkGoldenRod: ColorHex('#B8860BFF'),
    darkGrey: ColorHex('#A9A9A9FF'),
    darkGray: ColorHex('#A9A9A9FF'),
    darkKhaki: ColorHex('#BDB76BFF'),
    darkMagenta: ColorHex('#8B008BFF'),
    darkOliveGreen: ColorHex('#556B2FFF'),
    darkOrange: ColorHex('#FF8C00FF'),
    darkOrchid: ColorHex('#9932CCFF'),
    darkSalmon: ColorHex('#E9967AFF'),
    darkSeaGreen: ColorHex('#8FBC8FFF'),
    darkSlateBlue: ColorHex('#483D8BFF'),
    darkSlateGray: ColorHex('#2F4F4FFF'),
    darkSlateGrey: ColorHex('#2F4F4FFF'),
    darkTurquoise: ColorHex('#00CED1FF'),
    darkViolet: ColorHex('#9400D3FF'),
    deepPink: ColorHex('#FF1493FF'),
    deepSkyBlue: ColorHex('#00BFFFFF'),
    dimGray: ColorHex('#696969FF'),
    dimGrey: ColorHex('#696969FF'),
    dodgerBlue: ColorHex('#1E90FFFF'),
    fireBrick: ColorHex('#B22222FF'),
    floralWhite: ColorHex('#FFFAF0FF'),
    forestGreen: ColorHex('#228B22FF'),
    fuchsia: ColorHex('#FF00FFFF'),
    gainsboro: ColorHex('#DCDCDCFF'),
    ghostWhite: ColorHex('#F8F8FFFF'),
    gold: ColorHex('#FFD700FF'),
    goldenRod: ColorHex('#DAA520FF'),
    gray: ColorHex('#808080FF'),
    grey: ColorHex('#808080FF'),
    greenYellow: ColorHex('#ADFF2FFF'),
    honeyDew: ColorHex('#F0FFF0FF'),
    hotPink: ColorHex('#FF69B4FF'),
    indianRed: ColorHex('#CD5C5CFF'),
    indigo: ColorHex('#4B0082FF'),
    ivory: ColorHex('#FFFFF0FF'),
    khaki: ColorHex('#F0E68CFF'),
    lavender: ColorHex('#E6E6FAFF'),
    lavenderBlush: ColorHex('#FFF0F5FF'),
    lawnGreen: ColorHex('#7CFC00FF'),
    lemonChiffon: ColorHex('#FFFACDFF'),
    lightCoral: ColorHex('#F08080FF'),
    lightCyan: ColorHex('#E0FFFFFF'),
    lightGoldenRodYellow: ColorHex('#FAFAD2FF'),
    lightGray: ColorHex('#D3D3D3FF'),
    lightGrey: ColorHex('#D3D3D3FF'),
    lightPink: ColorHex('#FFB6C1FF'),
    lightSalmon: ColorHex('#FFA07AFF'),
    lightSeaGreen: ColorHex('#20B2AAFF'),
    lightSkyBlue: ColorHex('#87CEFAFF'),
    lightSlateGray: ColorHex('#778899FF'),
    lightSlateGrey: ColorHex('#778899FF'),
    lightSteelBlue: ColorHex('#B0C4DEFF'),
    lightYellow: ColorHex('#FFFFE0FF'),
    lime: ColorHex('#00FF00FF'),
    limeGreen: ColorHex('32CD32FF'),
    linen: ColorHex('#FAF0E6FF'),
    magenta: ColorHex('#FF00FFFF'),
    maroon: ColorHex('#800000FF'),
    mediumAquaMarine: ColorHex('#66CDAAFF'),
    mediumBlue: ColorHex('#0000CDFF'),
    mediumOrchid: ColorHex('#BA55D3FF'),
    mediumPurple: ColorHex('#9370DBFF'),
    mediumSeaGreen: ColorHex('#3CB371FF'),
    mediumSlateBlue: ColorHex('#7B68EEFF'),
    mediumSpringGreen: ColorHex('#00FA9AFF'),
    mediumTurquoise: ColorHex('#48D1CCFF'),
    mediumVioletRed: ColorHex('#C71585FF'),
    midnightBlue: ColorHex('#191970FF'),
    mintCream: ColorHex('#F5FFFAFF'),
    mistyRose: ColorHex('#FFE4E1FF'),
    moccasin: ColorHex('#FFE4B5FF'),
    navajoWhite: ColorHex('#FFDEADFF'),
    navy: ColorHex('#000080FF'),
    oldLace: ColorHex('#FDF5E6FF'),
    olive: ColorHex('#808000FF'),
    oliveDrab: ColorHex('#6B8E23FF'),
    orange: ColorHex('#FFA500FF'),
    orangeRed: ColorHex('#FF4500FF'),
    orchid: ColorHex('#DA70D6FF'),
    paleGoldenRod: ColorHex('#EEE8AAFF'),
    paleGreen: ColorHex('#98FB98FF'),
    paleTurquoise: ColorHex('#AFEEEEFF'),
    paleVioletRed: ColorHex('#DB7093FF'),
    papayaWhip: ColorHex('#FFEFD5FF'),
    peachPuff: ColorHex('#FFDAB9FF'),
    peru: ColorHex('#CD853FFF'),
    pink: ColorHex('#FFC0CBFF'),
    plum: ColorHex('#DDA0DDFF'),
    powderBlue: ColorHex('#B0E0E6FF'),
    purple: ColorHex('#800080FF'),
    rebeccaPurple: ColorHex('#663399FF'),
    rosyBrown: ColorHex('#BC8F8FFF'),
    royalBlue: ColorHex('#4169E1FF'),
    saddleBrown: ColorHex('#8B4513FF'),
    salmon: ColorHex('#FA8072FF'),
    sandyBrown: ColorHex('#F4A460FF'),
    seaGreen: ColorHex('#2E8B57FF'),
    seaShell: ColorHex('#FFF5EEFF'),
    sienna: ColorHex('#A0522DFF'),
    silver: ColorHex('#C0C0C0FF'),
    skyBlue: ColorHex('#87CEEBFF'),
    slateBlue: ColorHex('#6A5ACDFF'),
    slateGray: ColorHex('#708090FF'),
    slateGrey: ColorHex('#708090FF'),
    snow: ColorHex('#FFFAFAFF'),
    springGreen: ColorHex('#00FF7FFF'),
    steelBlue: ColorHex('#4682B4FF'),
    tan: ColorHex('#D2B48CFF'),
    teal: ColorHex('#008080FF'),
    thistle: ColorHex('#D8BFD8FF'),
    tomato: ColorHex('#FF6347FF'),
    turquoise: ColorHex('#40E0D0FF'),
    violet: ColorHex('#EE82EEFF'),
    wheat: ColorHex('#F5DEB3FF'),
    whiteSmoke: ColorHex('#F5F5F5FF'),
    yellow: ColorHex('#FFFF00FF'),
    yellowGreen: ColorHex('#9ACD32FF'),
}